from __future__ import annotations

import json
import importlib
import importlib.util
import sys
from datetime import datetime
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[3]
FOLDS_DIR = REPO_ROOT / "research" / "kt-bench" / "folds"
KT_BENCH_DIR = REPO_ROOT / "research" / "kt-bench"
POJ_ALLOWED_RESULTS = {
    "Accepted",
    "Wrong Answer",
    "Compile Error",
    "Time Limit Exceeded",
    "Memory Limit Exceeded",
    "Runtime Error",
    "Output Limit Exceeded",
    "Presentation Error",
    "System Error",
    "Validator Error",
}


def _load_accoding_adapter():
    path = KT_BENCH_DIR / "adapters" / "accoding_to_poj.py"
    spec = importlib.util.spec_from_file_location("accoding_to_poj", path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_folds_schema() -> None:
    for dataset in ("nips2020", "accoding"):
        path = FOLDS_DIR / f"{dataset}_folds.json"
        raw = json.loads(path.read_text(encoding="utf-8"))

        assert raw["dataset"] == dataset
        assert raw["source"] == "pykt.preprocess.split_datasets.KFold_split"
        assert len(raw["folds"]) == 5

        for expected_fold, fold in enumerate(raw["folds"]):
            train_indices = set(fold["train_indices"])
            test_indices = set(fold["test_indices"])

            assert fold["fold"] == expected_fold
            assert train_indices
            assert test_indices
            assert train_indices.isdisjoint(test_indices)


def test_sequences_sidecar_schema() -> None:
    for dataset in ("nips2020", "accoding"):
        path = FOLDS_DIR / f"{dataset}_sequences.csv"
        if not path.exists():
            pytest.skip(f"{path.name} is generated by research/kt-bench/preprocess.py")
        header, first = path.read_text(encoding="utf-8").splitlines()[:2]

        assert header == "row_index,order,skill,correct"
        row_index, order, skill, correct = first.split(",")
        assert int(row_index) >= 0
        assert int(order) >= 0
        assert skill
        assert correct in {"0", "1"}


def test_accoding_log_schema_fixture(tmp_path: Path) -> None:
    adapter = _load_accoding_adapter()
    sql = [
        "INSERT INTO `submissions` VALUES (1, 'c++', 'CE', 0, 0, 0, 3, 'comma, ok', 7, 11, NULL);\n",
        "INSERT INTO `submissions` VALUES (2, 'c++', 'AC', 1, 0, 0, 3, '', 7, 12, NULL);\n",
        "INSERT INTO `submissions` VALUES (3, 'c++', 'JG', 0, 0, 0, 3, '', 7, 13, NULL);\n",
    ]
    out = tmp_path / "poj_log.csv"

    stats = adapter.convert_sql_to_poj(sql=sql, out=out, max_learners=0, max_rows=0, seed=1)
    rows = out.read_text(encoding="utf-8").splitlines()

    assert rows[0] == "User,Problem,Result,Submit Time"
    assert rows[1].split(",") == ["7", "11", "Wrong Answer", "2016-01-01 00:00:01"]
    assert rows[2].split(",") == ["7", "12", "Accepted", "2016-01-01 00:00:02"]
    assert stats.rows_in == 3
    assert stats.rows_kept == 2
    assert stats.rows_dropped_nonterminal == 1


def test_accoding_log_schema_if_landed() -> None:
    path = KT_BENCH_DIR / "data" / "poj" / "poj_log.csv"
    if not path.exists():
        pytest.skip("ACcoding landing file is generated locally and gitignored")

    with path.open(encoding="utf-8") as fh:
        header = fh.readline().strip()
        assert header == "User,Problem,Result,Submit Time"
        for index, line in enumerate(fh):
            if index >= 1000:
                break
            user, problem, result, submit_time = line.rstrip("\n").split(",")
            assert int(user) > 0
            assert int(problem) > 0
            assert result in POJ_ALLOWED_RESULTS
            datetime.strptime(submit_time, "%Y-%m-%d %H:%M:%S")


def _write_result(
    results_dir: Path,
    *,
    dataset: str = "nips2020",
    model: str = "dkt",
    fold: int = 0,
    k: str | int = "full",
    auc: float = 0.75,
    ece: float | None = None,
) -> None:
    suffix = "ece" if k == "ece" else f"k{k}"
    path = results_dir / f"{dataset}__{model}__fold{fold}__{suffix}.json"
    payload = {
        "dataset": dataset,
        "model": model,
        "fold": fold,
        "k": k,
        "auc": auc,
        "y_true": [1, 0, 1, 0],
        "y_score": [0.9, 0.8, 0.4, 0.1],
        "_provenance": {"seed": 1, "folds_hash": "fixture", "folds_raw_source": "public_raw"},
    }
    if ece is not None:
        payload["ece"] = ece
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def test_join_reports_missing_cells_as_gaps(tmp_path: Path) -> None:
    from research_comparison.kt.join import join_kt_results

    results_dir = tmp_path / "kt"
    _write_result(results_dir, dataset="nips2020", model="dkt", fold=0, k="full", auc=0.75)
    _write_result(results_dir, dataset="nips2020", model="dkt", fold=0, k=3, auc=0.70)
    _write_result(results_dir, dataset="nips2020", model="dkt", fold=0, k="ece", ece=0.2)

    summary = join_kt_results(
        results_dir,
        expected_datasets=["nips2020"],
        expected_models=["dkt", "akt"],
        expected_folds=[0],
        expected_k_values=["full", 3],
    )

    assert summary["full_seq_auc"]["nips2020"]["dkt"] == pytest.approx(0.75)
    assert summary["coldstart_auc"][0]["auc"] == pytest.approx(0.70)
    assert summary["ece"]["nips2020"]["dkt"] == pytest.approx(0.2)
    assert {
        "dataset": "nips2020",
        "model": "akt",
        "fold": 0,
        "k": "full",
    } in summary["gaps"]


def test_join_boundary_does_not_import_torch_or_pykt() -> None:
    sys.modules.pop("research_comparison.kt.join", None)
    sys.modules.pop("torch", None)
    sys.modules.pop("pykt", None)

    importlib.import_module("research_comparison.kt.join")

    assert "torch" not in sys.modules
    assert "pykt" not in sys.modules


def test_expected_calibration_error_matches_hand_computed_value() -> None:
    from research_comparison.kt.join import expected_calibration_error

    ece, bins = expected_calibration_error(
        y_true=[1, 0, 1, 0],
        y_score=[0.9, 0.8, 0.4, 0.1],
        n_bins=2,
    )

    assert ece == pytest.approx(0.3)
    assert bins == [
        {"lower": 0.0, "upper": 0.5, "count": 2, "accuracy": 0.5, "confidence": 0.25},
        {"lower": 0.5, "upper": 1.0, "count": 2, "accuracy": 0.5, "confidence": 0.85},
    ]
